name: micro-servico-processador-video

services:
  backendprincipal:
    build: .
    container_name: worker_api
    ports:
      - "3000:3000"
      - "9464:9464"
    env_file:
      - .env
    volumes:
      - D:/VIDEOS:/data/videos
    networks:
      - app-network-externa

networks:
  app-network-externa:
    external: true