apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: processadorvideo-videos-pvc
  namespace: processamentovideo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
