apiVersion: v1
kind: Service
metadata:
  name: processadorvideo
  namespace: processamentovideo
  labels:
    app: processadorvideo
spec:
  selector:
    app: processadorvideo
  ports:
    - name: metrics
      port: 9464
      targetPort: metrics
      nodePort: 30000
  type: NodePort
  # type: ClusterIP
